forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib',
    :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod 'ntp',
    :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

mod 'apt',
    :git => 'https://github.com/puppetlabs/puppetlabs-apt.git'
